project:
  type: website

website:
  title: "Historia da Música 4º"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
#    theme: cosmo
    theme: sketchy
    css: styles.css

editor: visual

