project:
  type: website

website:
  title: "Coñecendo a Historia da Música (I)"
  navbar:
    right:
      - text: "Sobre o autor"
        href: about.qmd

    left: 
      - text: "Docencia"
        href: docencia.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

